### ISSUE TITLE
Date sorting?

### ISSUE THREAD

**Issue by gingerbeardman** [Thomasorus/Chisai#1]
Is it possible to use YYYY-MM-DD  for dates so that they're sorted chronologically?

Thanks!

**Comment by Thomasorus** [comment]
When you say sorted, you mean sorted inside the github listing or on your built website?

**Comment by gingerbeardman** [comment]
Inside GitHub/filesystem. So I can easily find a post from a specific date.

But of course they should also be sorted reverse chronologically on the built website.

**Comment by Thomasorus** [comment]
Hum I see.

The thing is, I can't modify it right now because other people are already using it and I don't want to break it for them if they try to update to the last version. It would probably be better to have an option in the `config.py` file to allow you to change it.

I'll look into that and will let you know when it's done.

**Comment by gingerbeardman** [comment]
Thanks!

It's annoying GitHub does not have sorted. It was asked for 5 years ago and they still have not introduced it.

**Comment by Thomasorus** [comment]
I've made a branch with the ISO date format. 

In config.py, you now can select EU or ISO on the last line to define if you want to name your text files with the EU format (day-month-year) or the ISO format (year-month-day).

The local testing found no bug I'd be more reassured if you tried this branch first. Try fork it from here: https://github.com/Thomasorus/Chisai/tree/iso-date

**Comment by Thomasorus** [comment]
ISO date support has been merged into main branch.

**Comment by gingerbeardman** [comment]
Sorry that I did not report back!
